# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/0_sbram/sram_i64o64_d256/sram_i64o64_d256.xci
# IP: The module: 'sram_i64o64_d256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/0_sbram/sram_i64o64_d256/sram_i64o64_d256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_i64o64_d256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/0_sbram/sram_i64o64_d256/sram_i64o64_d256.xci
# IP: The module: 'sram_i64o64_d256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/0_sbram/sram_i64o64_d256/sram_i64o64_d256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_i64o64_d256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
