# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048.xci
# IP: The module: 'afifo_i72o72_d2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048.xci
# IP: The module: 'afifo_i72o72_d2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/sim_demo20200320/rtl/00_xilinx_ip/1_afifo/afifo_i72o72_d2048/afifo_i72o72_d2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_i72o72_d2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
