@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Apr 16 14:39:34 +0800 2025
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto c61293ade1f6433c9deda9ef0104f2d5 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L fifo_generator_v13_2_5 -L srio_gen2_v4_1_11 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot srio_sim_behav xil_defaultlib.srio_sim xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto c61293ade1f6433c9deda9ef0104f2d5 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L fifo_generator_v13_2_5 -L srio_gen2_v4_1_11 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot srio_sim_behav xil_defaultlib.srio_sim xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
