# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/srio_5gx1.xci
# IP: The module: 'srio_5gx1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/srio_5gx1_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'srio_5gx1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/synth/srio_5gx1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'srio_5gx1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/srio_5gx1.xci
# IP: The module: 'srio_5gx1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/srio_5gx1_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'srio_5gx1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/02_srio/srio_5gx1/synth/srio_5gx1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'srio_5gx1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
