# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512.xci
# IP: The module: 'sfifo_i64o64_d512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_i64o64_d512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_i64o64_d512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512.xci
# IP: The module: 'sfifo_i64o64_d512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_i64o64_d512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/00_module/07_fpga/develop_20200323/rtl/00_xilinx_ip/01_sfifo/sfifo_i64o64_d512/sfifo_i64o64_d512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_i64o64_d512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
